const articles = [
  {
    id: 1,
    h4: "Actual - Mai 2021 to ongoing",
    h5: "Web Developper Training",
    div1: "Training in HTML/CSS/Javascript/React/Svelte/GraphQL/Solidity/Ethereum Blockchain development.",
    div2: "",
    div3: "",
    div4: "",
  },
  {
    id: 2,
    h4: "September 2019 to April 2021",
    h5: "Trainée at Compagnons du Devoir, Paris, France",
    div1: "Training as system installer of thermal plants.",
    div2: "",
    div3: "",
    div4: "",
  },
  {
    id: 3,
    h4: "Mai 2011 to June 2019 - Sanofi, Paris",
    h5: "Technical Service Architect",
    div1: "Responsible of technical infrastructure and associated services for the ETL/Informatica/Teradata/SAS services",
    div2: "Design and implementation of shared platforms with associated technical services.",
    div3: "Migration and replatforming of business projects from the legacy perimeter towards global datacenter platforms - onboarding of new projects, deployment,access management.",
    div4: "Training and onboarding for the support teams of Level 2 and 3 to take in charge the perimeter.",
  },
  {
    id: 4,
    h4: "October 2008 to April 2011 - Sanofi, Paris",
    h5: "SAP Technical Administrator",
    div1: "Administration of company's SAP systems in production environment. Incident resolution, cloning, patching/upgrades for ECC/BI7/Netweaver plateforms with high constraints on availability, security and reliability, in a SOA/GxP compliant systems.",
    div2: "",
    div3: "",
    div4: "",
  },
  {
    id: 5,
    h4: "December 2006 to October 2008 - Sanofi-Aventis, Paris, France",
    h5: "Database Administrator (Development DBA)",
    div1: "Infocentre Purchasing : datawarehouse data loading (70 GB online), partitioning and SQL query tuning, UNICODE migration of all databases representing the shared platform, providing technical and architectural expertise to the development team.",
    div2: "Legal licenses database : query tuning, definition of deployment procedures for databases and applications using J2EE/ADF and Oracle Virtual Private Database.",
    div3: "Datawarehouse for accidents: development of Oracle OLAP cubes and deployment procedures.",
    div4: "",
  },
  {
    id: 6,
    h4: "August 2002 to November 2006 - ILOG, Paris, France",
    h5: "Database Administrator",
    div1: "Reporting/Financial data mart: schema design and development of stored procedures for revenue recognition, consolidation and data integration at the group level, budget reporting (Arcplan Dynasight/Essbase).",
    div2: "Schema design and application development for computing sales commissioning using Oracle - ILOG JRules integration.",
    div3: "BI project (Business Intelligence): development of dashboards for analyzing sales cycle and opportunities forecast (Oracle DataMiner / Arcplan Dynasight).",
    div4: "",
  },
  {
    id: 7,
    h4: "September 2000 to July 2002 - Béton de France - RMC Groupe Services, Paris, France",
    h5: "Oracle DBA",
    div1: "Management of the replication data-flow between SAP, EAI (Mercator) and Oracle within a hybrid environment, Solaris-WindowsNT WS, composed of 60 production databases distributed around all France. Automation, architecture updates.",
    div2: "Design, implementation and maintenance of ETL processes and ODS schema for a data warehouse containing data mart sales cubes.",
    div3: "",
    div4: "",
  },
  {
    id: 8,
    h4: "November 1999 to August 2000",
    h5: "Database consultant, Bucharest, Romania",
    div1: "Missions for SMB - installation and configuration of accounting applications, Novell networks maintenance.",
    div2: "",
    div3: "",
    div4: "",
  },
  {
    id: 9,
    h4: "February 1999 to October 1999 - SIVECO, Bucharest, Romania",
    h5: "Programmer/Analyst (collaboration during military duty, then full-time employee)",
    div1: "Developer for Siveco Applications - an ERP system for enterprise management - development of modules for human resources,payroll and fixed assets.",
    div2: "Developing custom backup and recovery procedures for client's databases, and developing custom programs to migrate data from Cobol to Oracle.",
    div3: "",
    div4: "",
  },
  {
    id: 10,
    h4: "November 1998 to April 1999 - Military duty, Romanian Defense Minister",
    h5: "Financial and Accounting Department Service",
    div1: "In charge to install Windows NT Server/Oracle/Forms 4.5 and different applications for military schools in Bucharest.",
    div2: "",
    div3: "",
    div4: "",
  },
  {
    id: 11,
    h4: "October 1997 to October 1998 - Vinexport Trading Company, Bucharest, Romania",
    h5: "Programmer/Analyst",
    div1: "Development and maintenance of an invoices tracking system for external (foreign currencies) and internal client's transactions.",
    div2: "Migration of existing accounting and payroll applications to Oracle/Forms/Reports technology.",
    div3: "",
    div4: "",
  },
];
const trainings = [
  {
    id: 1,
    text: "2022 - Certified Ethereum Developer - Blockchain Council",
  },
  {
    id: 2,
    text: "2022 - Certified Solidity Developer(CSD) - Blockchain Council",
  },
  {
    id: 3,
    text: "2007 - Introduction to CMMI",
  },
  {
    id: 4,
    text: "2006 - OCP DBA Oracle 10g",
  },
  {
    id: 5,
    text: "November 2003 - Certification SAP Technical Consultant (Administration) - mySAP Technology",
  },
  {
    id: 6,
    text: "2002-2003 - Oracle administration certifications - OCP DBA Oracle 8, 8i, 9i",
  },
];
export async function get() {
  return {
    status: 200,
    body: {
      articles,
      trainings,
    },
  };
}
